# Generated by Django 3.0.1 on 2020-01-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200101_0537'),
        ('events', '0004_auto_20200101_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendants',
            field=models.ManyToManyField(blank=True, to='contacts.Contact'),
        ),
    ]
