# Generated by Django 3.0.1 on 2019-12-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Full name')),
                ('job_title', models.CharField(max_length=62, verbose_name='Job title')),
                ('company', models.CharField(max_length=254, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=14, verbose_name='Contact Number')),
                ('notes', models.CharField(max_length=508, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
