# Generated by Django 3.0.1 on 2019-12-31 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20191231_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
