# Generated by Django 3.0.1 on 2020-01-01 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_pid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-modified',), 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
