databases:
  default:
    ENGINE: 'django.db.backends.postgresql'
    NAME: 'some_db'
    USER: 'some_user'
    PASSWORD: '4dm1n4dm1n'
    # Name of the container on host
    HOST: 'localhost'
    PORT: '5432'

secret_key: 'a1c3b5bD$tzgy^i78uhb4o#&+fx7kmtz-l8v3(u^0&an3h@3m=kw'

allowed_hosts:
  - 'example.com'
  - '127.0.0.1'
