databases:
  default:
    ENGINE: 'django.db.backends.postgresql'
    NAME: 'webinar_db'
    USER: 'webinar_user'
    PASSWORD: '4dm1n4dm1n'
    # Name of the container on host
    HOST: 'localhost'
    PORT: '54321'

secret_key: '1@6q9hYo1i$!e2+!@#vgz-m!#h0)v5ag(4=mo-69w+!ngm*)xK'

allowed_hosts:
  - '127.0.0.1'
  - 'localhost'
